@startuml Message_State
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_State.puml

[*] --> Created: Message Created
Created --> Delivered: Delivery Attempted
Delivered --> Acknowledged: Client Acknowledges
Delivered --> RetryQueue: Delivery Failed
RetryQueue --> Delivered: Retry Attempt
RetryQueue --> Expired: Max Retries Exceeded\nor Timeout Reached
Acknowledged --> [*]
Expired --> [*]

state RetryQueue {
    [*] --> Waiting
    Waiting --> RetryingDelivery: User Connected
    RetryingDelivery --> Waiting: Delivery Failed
}

@enduml